system:
    name: minimal
    type: vmx-14 vmx-20
    os_vmw: vmw.vmwarePhoton64Guest

networks:
    vm_network:
        name: "None"
        description: "The None network"

hardware:
    cpus: 2
    memory:
        type: memory
        size: 4096
    nvme1:
        type: nvme_controller
    sata1:
        type: sata_controller
    cdrom1:
        type: cd_drive
        parent: sata1
    rootdisk:
        type: hard_disk
        parent: nvme1
        disk_image: dummy.vmdk
    usb1:
        type: usb_controller
    ethernet1:
        type: ethernet
        subtype: VmxNet3
        network: vm_network
    videocard1:
        type: video_card
    vmci1:
        type: vmci
